// Mapping bank names (lowercase) to OY Disbursement Bank Codes
export const oyCodeMap: Record<string, string> = {
  "bank rakyat indonesia": "002",
  "bank mandiri": "008",
  "bni (bank negara indonesia)": "009",
  "bank danamon": "011",
  "permata": "013",
  "bank central asia": "014",
  "maybank indonesia": "016",
  "panin bank": "019",
  "cimb niaga": "022",
  "tmrw/uob": "023",
  "bank ocbc nisp": "028",
  "citibank": "031",
  "jp morgan chase indonesia": "032",
  "bank china construction bank indonesia": "036",
  "bank artha graha internasional": "037",
  "bank of tokyo mitsubishi ufj": "042",
  "dbs indonesia": "046",
  "standard chartered bank": "050",
  "bank capital indonesia": "054",
  "anz indonesia": "061",
  "deutsche bank ag": "067",
  "bank of china (hong kong) limited": "069",
  "bank bumi arta": "076",
  "hsbc indonesia": "087",
  "bank antardaerah": "088",
  "rabobank": "089",
  "bank mutiara (jtrust)": "095",
  "bank mayapada": "097",
  "bjb": "110",
  "bank dki": "111",
  "bank bpd diy": "112",
  "bank bpd diy syariah": "112s",
  "bank jateng": "113",
  "bank jatim": "114",
  "bank jatim syariah": "114s",
  "bank jambi": "115",
  "bank jambi syariah": "115s",
  "bank aceh syariah": "116",
  "bank sumut": "117",
  "bank sumut syariah": "117s",
  "bank sumbar/nagari": "118",
  "bank sumbar/nagari syariah": "118s",
  "bank riau kepri": "119",
  "bank sumsel babel": "120",
  "bank sumsel babel syariah": "120s",
  "bank lampung": "121",
  "bank kalsel": "122",
  "bank kalsel syariah": "122s",
  "bank kalbar": "123",
  "bank kalbar syariah": "123s",
  "bank kaltim / kaltimtara": "124",
  "bank kaltim syariah": "124s",
  "bank kalteng": "125",
  "bank sulselbar": "126",
  "bank sulselbar syariah": "126s",
  "bank sulutgo": "127",
  "bank ntb syariah": "128",
  "bpd bali": "129",
  "bank ntt": "130",
  "bank maluku": "131",
  "bank papua": "132",
  "bank bengkulu": "133",
  "bank sulteng (sulawesi tengah)": "134",
  "bank sultra": "135",
  "bpd banten": "137",
  "panin dubai syariah": "145",
  "bank of india indonesia": "146",
  "muamalat": "147",
  "bank mestika dharma": "151",
  "bank sinarmas": "153",
  "bank maspion indonesia": "157",
  "bank ganesha": "161",
  "icbc indonesia": "164",
  "qnb indonesia": "167",
  "btn": "200",
  "btn syariah": "200s",
  "bank woori saudara (hs 1906)": "212",
  "smbc indonesia": "213",
  "bank victoria international": "566",
  "bank victoria international syariah": "405",
  "bjb syariah": "425",
  "bank mega": "426",
  "bank bukopin": "441",
  "bsi (bank syariah indonesia)": "451",
  "bank jasa jakarta": "472",
  "line bank/keb hana": "484",
  "motion/mnc bank": "485",
  "neo commerce/yudha bhakti": "490",
  "nobu (nationalnobu) bank": "503",
  "bank mega syariah": "506",
  "bank ina perdana": "513",
  "permata syariah": "517",
  "bank prima": "520",
  "bank bukopin syariah": "521",
  "bank sahabat sampoerna": "523",
  "bank dinar indonesia / oke bank": "526",
  "seabank/bank kesejahteraan ekonomi": "535",
  "bank central asia syariah": "536",
  "bank jago / artos": "542",
  "bank jago syariah": "542s",
  "bank btpn syariah": "547",
  "bank multi arta sentosa / bank mas": "548",
  "bank hibank indonesia": "553",
  "bank index selindo": "555",
  "bank cnb (centratama nasional bank)": "559",
  "superbank": "562",
  "bank mantap (mandiri taspen)": "564",
  "allo bank/bank harda internasional": "567",
  "atmb lsb": "600",
  "bpr ks": "688",
  "bank dki syariah": "724",
  "bank jateng syariah": "725",
  "bank sinarmas syariah": "734",
  "finnet": "777",
  "bank eka": "867",
  "bank ibk indonesia / agris": "945",
  "ctbc (chinatrust) indonesia": "949",
  "commonwealth bank": "950",
  "atmb plus": "987",
  "dana": "dana",
  "gopay": "gopay",
  "linkaja": "linkaja",
  "ovo": "ovo",
  "shopeepay": "shopeepay"
};
