openapi: 3.0.0
info:
  title: Payment API
  version: 1.0.0
paths:
  /create-order:
    post:
      summary: Create an aggregated order
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderRequest"
      responses:
        "200":
          description: Order created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
  /:
    post:
      summary: Create a direct transaction
      security:
        - apiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "200":
          description: Order created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
  /transaction/callback:
    post:
      summary: Payment gateway callback
      responses:
        "200":
          description: Callback processed
  /order/{id}:
    get:
      summary: Retrieve order details by ID
      security:
        - apiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Order details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderResponse"
  /transaction/callback/gidi:
    post:
      summary: GIDI payment callback
      responses:
        "200":
          description: Callback processed
  /order/{id}/status:
    get:
      summary: Check payment status by order ID
      security:
        - apiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Payment status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentStatus"
  /transaction/callback/oy/retry/{referenceId}:
    post:
      summary: Retry OY! callback
      parameters:
        - in: path
          name: referenceId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Retry processed
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key
  schemas:
    Transaction:
      type: object
      required:
        - merchantName
        - price
        - buyer
        - subMerchantId
        - sourceProvider
      properties:
        merchantName:
          type: string
          description: gv / hilogate / …
        price:
          type: number
        buyer:
          type: string
        flow:
          type: string
          enum:
            - embed
            - redirect
        playerId:
          type: string
        subMerchantId:
          type: string
        sourceProvider:
          type: string
    OrderRequest:
      type: object
      required:
        - amount
        - userId
      properties:
        amount:
          type: number
          minimum: 1
        userId:
          type: string
        playerId:
          type: string
    OrderResponse:
      type: object
      properties:
        orderId:
          type: string
        checkoutUrl:
          type: string
        qrPayload:
          type: string
        playerId:
          type: string
        totalAmount:
          type: number
        expiredTs:
          type: string
    PaymentStatus:
      type: object
      properties:
        status:
          type: string
tags: []
