openapi: 3.0.0
info:
  title: Withdrawal API
  version: 1.0.0
paths:
  /validate-account:
    post:
      summary: Validate destination account
      security:
        - clientAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ValidateAccountRequest"
      responses:
        "200":
          description: Account validated
  /:
    post:
      summary: Create a new withdrawal
      security:
        - clientAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WithdrawalRequest"
      responses:
        "200":
          description: Withdrawal created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WithdrawalResponse"
    get:
      summary: List all withdrawals for this client
      security:
        - clientAuth: []
      responses:
        "200":
          description: List of withdrawals
  /submerchants:
    get:
      summary: List sub merchants
      security:
        - clientAuth: []
      responses:
        "200":
          description: List of sub merchants
  /{id}/retry:
    post:
      summary: Retry a failed withdrawal
      security:
        - clientAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Retry initiated
components:
  securitySchemes:
    clientAuth:
      type: http
      scheme: bearer
  schemas:
    ValidateAccountRequest:
      type: object
      required:
        - bank_code
        - account_number
      properties:
        bank_code:
          type: string
          pattern: ^[0-9]{3}$
        account_number:
          type: string
    WithdrawalRequest:
      type: object
      required:
        - amount
        - account_no
        - bank_code
        - currency
        - request_id
      properties:
        amount:
          type: integer
          minimum: 1
        account_no:
          type: string
        bank_code:
          type: string
          pattern: ^[0-9]{3}$
        currency:
          type: string
          minLength: 3
          maxLength: 3
        description:
          type: string
        request_id:
          type: string
          format: uuid
    WithdrawalResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
tags: []
